-- MySQL Script generated by MySQL Workbench
-- Mon May 27 21:51:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetCnam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetCnam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetCnam` DEFAULT CHARACTER SET utf8 ;
USE `projetCnam` ;

-- -----------------------------------------------------
-- Table `projetCnam`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetCnam`.`Utilisateur` (
  `id_ARA` VARCHAR(50) NOT NULL,
  `Mail` VARCHAR(100) NOT NULL,
  `MDP` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_ARA`),
  UNIQUE INDEX `Mail_UNIQUE` (`Mail` ASC) VISIBLE,
  UNIQUE INDEX `id_ARA_UNIQUE` (`id_ARA` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
